### ISSUE TITLE
Test children.html

### ISSUE THREAD

**Issue by jacobbuettner** [joshuarichard/amgg#110]
Try and break children.html, document any problems you find in this issue.

**Comment by jacobbuettner** [comment]
Birthday dropdown does not line up with the button in Edge
![image](https://cloud.githubusercontent.com/assets/8673790/12538382/89dd2046-c2a6-11e5-999e-0c90e2682214.png)

The button and the dropdown are in the same div, this is what is causing the issue.  Move the button outside of the dropdown div to resolve the issue and restyle the button so it does not span the entire box and is right aligned

**Comment by jacobbuettner** [comment]
Search button outside of Find a Child box in Firefox
![2016-01-24 5](https://cloud.githubusercontent.com/assets/8673790/12538396/cab40be8-c2a6-11e5-95b0-06f96f542acb.png)

**Comment by joshuarichard** [comment]
let's close this and open them up as they come up. i'm sure we're going to have a tone now that we get into testing.
