### ISSUE TITLE
get find a child working

### ISSUE THREAD

**Issue by joshuarichard** [joshuarichard/amgg#116]
1) open up `GET /api/v1/findchild/:selector` as an api route
2) client side code to get the fields selected and combine into selector variable (json)
3) send `GET /api/v1/findchild/JSON.stringify(selector)`
4) get back children
5) delete all slides in the owl carousel
6) add in 5 new slides that match the find a child selection

**Comment by joshuarichard** [comment]
Everything for this issue is done except for birthday, birth month, and deleting the existing kids from the slider

**Comment by jacobbuettner** [comment]
The add another child button under the slider does not add children of the same type specified by the find a child box.  I specified masculino which loaded 5 masculino children as expected, but when I clicked add another child it added mujer.

![image](https://cloud.githubusercontent.com/assets/8673790/12753623/de026424-c995-11e5-9f16-658ee118972d.png)

**Comment by joshuarichard** [comment]
stale issue, everything's done except for birth month/birth day which is #120
