### ISSUE TITLE
Test checkout.html

### ISSUE THREAD

**Issue by jacobbuettner** [joshuarichard/amgg#132]
Put any issues with the checkout page in this issue.

**Comment by jacobbuettner** [comment]
Login overlay should be right below the login button, see second screen shot
![image](https://cloud.githubusercontent.com/assets/8673790/12821033/a3ea602a-cb2f-11e5-8467-cae202554a5a.png)

![image](https://cloud.githubusercontent.com/assets/8673790/12821105/f90acdba-cb2f-11e5-8dc2-8dcd5ddf4a9b.png)

**Comment by joshuarichard** [comment]
let's close this and open them up as they come up. i'm sure we're going to have a tone now that we get into testing.
