### ISSUE TITLE
Donor's need to have a valid password

### ISSUE THREAD

**Issue by jacobbuettner** [joshuarichard/amgg#155]
We need to enforce standard password constraints.  Donor's should not be able to have a empty password when sponsoring a child.  We can avoid the empty password by making sure the password field is not empty, not sure how we want to tackle other validation (length, number, special char, etc.).

**Comment by joshuarichard** [comment]
right now donor's can't create accounts or sponsor children with an empty password, but password constraints would be good:

i'm thinking require:
1. must be at least 6 characters long
2. must have at least one lower case letter
3. must have at least one upper case letter
4. must have at least one number

**Comment by joshuarichard** [comment]
merged in #248
