### ISSUE TITLE
Get database requirements to help figure out if we should use couchDB or mysql

### ISSUE THREAD

**Issue by joshuarichard** [joshuarichard/amgg#16]
talk with brian, hopefully this will help us clear it up.

also hopefully we don't need to use mysql because then we probably shouldn't use node.... and that would change things.

**Comment by joshuarichard** [comment]
still working on this, very close though.

**Comment by joshuarichard** [comment]
related #6 .... maybe even the same task.

**Comment by jacobbuettner** [comment]
From our discussion with Dr. Tuck on 11/16 and research into Couch vs Mongo.  It looks like MongoDB is the best option for our project.  Mongo offers partition tolerance and consistency which are both very important for our project  Furthermore, Mongo queries are very similar to SQL queries which will make it easier for AMGG devs to understand with their experience with SQL.

**Comment by joshuarichard** [comment]
over and out.
