### ISSUE TITLE
Cannot load all sponsored children - account page

### ISSUE THREAD

**Issue by jacobbuettner** [joshuarichard/amgg#174]
If any of the donors sponsorship's does not load, we should either retry or alert the user that a connection cannot be established.

**Comment by jacobbuettner** [comment]
![image](https://cloud.githubusercontent.com/assets/8673790/13259031/b0b2c95c-da23-11e5-8340-88796e3b5ab2.png)

In this case, the donor has 2 sponsored children, but only one loaded.  The error message cannot establish a connection was logged to the console.  We should probably retry the call again in this case, and if we still cannot connect, alert the user

**Comment by joshuarichard** [comment]
closing this for now, let's reopen it and come back to it if it seems like it's a real issue
