### ISSUE TITLE
Project should not crash when it cannot find children

### ISSUE THREAD

**Issue by jacobbuettner** [joshuarichard/amgg#176]
If the app is unable to find the children in the cart, it crashes.  This should not be the case.

**Comment by jacobbuettner** [comment]
I encountered this bug when I had children ids from an old collection that do not exist in the endgame collection.  When the project queried for the children and could not find them, it crashed.  We should handle this with an alert to the user, or something like that

**Comment by joshuarichard** [comment]
Yeah so I don't think it crashed when it was looking for the child doc, I think it crashed when it was looking for the picture. I'll check both though

**Comment by joshuarichard** [comment]
Merged fix
