### ISSUE TITLE
Sponsor additional children with existing account

### ISSUE THREAD

**Issue by jacobbuettner** [joshuarichard/amgg#177]
If a donor already has an account, and they go the the checkout page to sponsor some children, they will get a 409 because an account already exists with the email they enter.  Instead, when a duplicate email address is detected, we should try and authentic the donor, and if it authenticates, update the donor account with the new sponsorship.  

If it does not validate, we should prompt them to create an account before sponsoring a child.

**Comment by joshuarichard** [comment]
![screenshot_2016-02-29-05-15-22](https://cloud.githubusercontent.com/assets/12897564/13391642/90242d32-dea3-11e5-95e5-a9ac0e2788c6.png)
Additional info

**Comment by joshuarichard** [comment]
merged in #207
