### ISSUE TITLE
Session Storage causing purchased children to appear in separate cart after purchase

### ISSUE THREAD

**Issue by compassface** [joshuarichard/amgg#187]

**Comment by compassface** [comment]
I figure this is a little confusing word-wise so this is the process of the bug that I found

**Comment by compassface** [comment]
![image](https://cloud.githubusercontent.com/assets/8681399/13381197/d5a6a6e4-de23-11e5-9304-42d2696b77ef.png)

buy child

**Comment by compassface** [comment]
![image](https://cloud.githubusercontent.com/assets/8681399/13381201/e8de7214-de23-11e5-89c4-132c6d751eb8.png)

child in account page

**Comment by compassface** [comment]
![image](https://cloud.githubusercontent.com/assets/8681399/13381204/fa257856-de23-11e5-8245-367772d39521.png)

buy second child

**Comment by compassface** [comment]
![image](https://cloud.githubusercontent.com/assets/8681399/13381209/1412fa18-de24-11e5-8d59-98748fc66820.png)

check second child out

**Comment by compassface** [comment]
![image](https://cloud.githubusercontent.com/assets/8681399/13381210/1e0a80cc-de24-11e5-8ba8-34ffc5e769b2.png)

both bought and un-bought children appear in checkout

**Comment by joshuarichard** [comment]
fixed https://github.com/joshuarichard/amgg/commit/f7bcffa6049aa7c51153f9b13b96905d378a3245
