### ISSUE TITLE
give donors the option to change their password on the account page

### ISSUE THREAD

**Issue by joshuarichard** [joshuarichard/amgg#215]
maybe we want to require them to type in their old password again, but if they have a valid token they've typed in their password already. - this will require a bit of api work.

**Comment by joshuarichard** [comment]
this should be a joint effort between me and you, @jacobbuettner.

i'll update the api and you add the account.js html elements. should we do a pop up? should we add it underneath the current form?

**Comment by jacobbuettner** [comment]
Add a forgot your password link to the login overlay

**Comment by jacobbuettner** [comment]
Moving "forgot password" functionality to #242 because its probably going be a pretty big undertaking

**Comment by joshuarichard** [comment]
merged
