### ISSUE TITLE
If donor is not sponsoring any kids then remove loading spinner

### ISSUE THREAD

**Issue by jacobbuettner** [joshuarichard/amgg#218]
When a donor goes to their account page and they do not have any sponsored children, we should remove the loading spinner and handle the following in the picture below.  We can either leave the sponsored children section blank with just the header, or we can put a link in back to children.html.

![image](https://cloud.githubusercontent.com/assets/8673790/13725073/9ab62f7c-e865-11e5-94d2-40438a2116dc.png)

**Comment by joshuarichard** [comment]
check the donor doc that gets returned to see if ninos_patracindor is either null or an empty array. if it is either of those then the donor isn't sponsoring any children so delete the spinner.

**Comment by joshuarichard** [comment]
merged. see above
