### ISSUE TITLE
design edits from juan

### ISSUE THREAD

**Issue by joshuarichard** [joshuarichard/amgg#223]
<img width="763" alt="screen shot 2016-03-13 at 6 54 30 pm" src="https://cloud.githubusercontent.com/assets/12897564/13731987/5ae29e60-e94d-11e5-91cc-87f0d5668bc2.png">
<img width="612" alt="screen shot 2016-03-13 at 6 54 36 pm" src="https://cloud.githubusercontent.com/assets/12897564/13731988/5ae2e56e-e94d-11e5-9bbd-067c8b8f648f.png">
<img width="750" alt="screen shot 2016-03-13 at 6 54 40 pm" src="https://cloud.githubusercontent.com/assets/12897564/13731989/5ae53a44-e94d-11e5-877c-21493bb4406d.png">
<img width="748" alt="screen shot 2016-03-13 at 6 54 46 pm" src="https://cloud.githubusercontent.com/assets/12897564/13731990/5ae54bb0-e94d-11e5-82fa-59fad1f5a653.png">

**Comment by jacobbuettner** [comment]
Opening this back up because we still need to update the styles across the site.

**Comment by jacobbuettner** [comment]
Nevermind, going to break this into smaller issues. Closing again
