### ISSUE TITLE
No cart on checkout page

### ISSUE THREAD

**Issue by jacobbuettner** [joshuarichard/amgg#233]
If the user manages to get to the checkout page without a cart then the js file will not properly execute.  See screenshot below.  The page should be able to load, and the loading spinner should be removed if there is no cart.  We want to let the user log in and click links even if they don't have a cart

![image](https://cloud.githubusercontent.com/assets/8673790/13848796/cdb2c670-ec29-11e5-89e0-5f632c350086.png)

**Comment by joshuarichard** [comment]
I noticed and fixed this in #214. Once that's merged we'll close this issue

**Comment by joshuarichard** [comment]
merged. see above
