### ISSUE TITLE
fix headers on children, checkout, and account pages

### ISSUE THREAD

**Issue by joshuarichard** [joshuarichard/amgg#237]
old:
<img width="1325" alt="screen shot 2016-03-18 at 8 01 29 pm" src="https://cloud.githubusercontent.com/assets/12897564/13894976/4aaeeff8-ed44-11e5-87f1-5da4013e468e.png">
new:
<img width="1305" alt="screen shot 2016-03-18 at 8 01 41 pm" src="https://cloud.githubusercontent.com/assets/12897564/13894977/4ab8bcb8-ed44-11e5-9407-3cfdfcf8c315.png">

**Comment by compassface** [comment]
was this in carlos' code or something?
