### ISSUE TITLE
Wrong error message when session times out on account page

### ISSUE THREAD

**Issue by jacobbuettner** [joshuarichard/amgg#241]
When a donor no longer has a valid login token, which will most likely happen when they try and go to their account page after their session expires, they get an error message saying "Unable to edit your information".  They should either get the correct error message and/or should be prompted to log in again.

This may also happen if they try navigating to the account page before they log in.

![image](https://cloud.githubusercontent.com/assets/8673790/13906861/8af7b5da-eeb7-11e5-8ec8-7a8f2b446728.png)

**Comment by joshuarichard** [comment]
i fixed this a while ago. you didn't have the latest master when you saw this
