### ISSUE TITLE
Forgot password option

### ISSUE THREAD

**Issue by jacobbuettner** [joshuarichard/amgg#242]
Users should be able to reset their password if they forgot it.  We've got two options that I can think of for implementing this functionality.

The normal process that I think of is we email the user a link where they reset their password.  We have email functionality setup but I do not know how to email them a unique and secure password reset link.

The other options I was thinking of is that we can email the user a key that they can enter along with their email address to reset their password.  We would have to store that key somewhere, probably in the donor doc with a ttl of an hour or something like that.

**Comment by joshuarichard** [comment]
merged
