### ISSUE TITLE
center spinner

### ISSUE THREAD

**Issue by joshuarichard** [joshuarichard/amgg#247]

**Comment by compassface** [comment]
where?

**Comment by joshuarichard** [comment]
Children page, I'm thinking just center it between the find a child panel and the left side of the page. Have fun with it though, and assign the pr to jake when it's time

**Comment by joshuarichard** [comment]
we're going to need to fix this towards the end, it's pretty centered right now, but the rest of the page is off. we'll have to do some of this towards the end when we fix some of the styling

**Comment by joshuarichard** [comment]
fyi: 
<img width="1440" alt="screen shot 2016-03-25 at 5 35 16 pm" src="https://cloud.githubusercontent.com/assets/12897564/14054518/4ac56794-f2b0-11e5-8e80-e3ddf1489432.png">
