### ISSUE TITLE
Mockup some MongoDB queries

### ISSUE THREAD

**Issue by jacobbuettner** [joshuarichard/amgg#26]
Start writing some mongo queries.  If we end up choosing mongo, which it looks like we will, then we will be able to use these later on down the road.

**Comment by jacobbuettner** [comment]
Created a MockQueries.txt on server. Add queries that we may use once the DB is created.  File located at /workspace/jake-amg/

**Comment by jacobbuettner** [comment]
Added a bunch of queries last night, should start looking into REST calls

**Comment by joshuarichard** [comment]
Mongo doesn't have a rest api they do everything over byte tcp/ip

**Comment by joshuarichard** [comment]
replaced by #32
