### ISSUE TITLE
Determine which cloud service we will use

### ISSUE THREAD

**Issue by jacobbuettner** [joshuarichard/amgg#27]
We need to determine which cloud service we will be using for our project.  I know we are leaning towards GoDaddy because they are using GoDaddy to host their websites.  We should investigate the services listed in the Rationale doc and any other we can think of and update the Rationale doc with our decision and reasoning.

**Comment by joshuarichard** [comment]
GoDaddy VPS should be the solution and it looks like we'll be sticking with this. reference #28. closing for now
