### ISSUE TITLE
Cart Link

### ISSUE THREAD

**Issue by compassface** [joshuarichard/amgg#272]
Basically just a link to the checkout page, right now we have no way of getting to the checkout page if the donor hits back or sponsor another child from the checkout page if they aren't logged in.

**Comment by joshuarichard** [comment]
Good idea

**Comment by jacobbuettner** [comment]
Getting a weird bug on the checkout page with the link appearance
![image](https://cloud.githubusercontent.com/assets/8673790/14620707/3e79fbfa-058c-11e6-9da9-759ceb86b98c.png)
