### ISSUE TITLE
Create account overlay

### ISSUE THREAD

**Issue by jacobbuettner** [joshuarichard/amgg#292]
After a user successfully creates an account using the create account overlay they are logged in and the login button in the top right changes to Mi Cuenta.  If the user clicks that button it will pop up the login overlay and then re-direct to the account page.  It should not open up the account overlay on that first click.

**Comment by joshuarichard** [comment]
yeah, i've noticed this a few times too, let's put this on the way back burner though.

**Comment by joshuarichard** [comment]
merged
