### ISSUE TITLE
sticky footer

### ISSUE THREAD

**Issue by joshuarichard** [joshuarichard/amgg#306]
fix the footer on all pages. way too much whitespace for most of them and there's overlapping in other instances:

look into this - https://getbootstrap.com/examples/sticky-footer/
or this - http://getbootstrap.com/examples/sticky-footer-navbar/

<img width="1396" alt="screen shot 2016-04-17 at 6 38 28 pm" src="https://cloud.githubusercontent.com/assets/12897564/14590575/04f20082-04cc-11e6-8e04-9904f7279e33.png">
<img width="1395" alt="screen shot 2016-04-17 at 6 38 37 pm" src="https://cloud.githubusercontent.com/assets/12897564/14590572/fea97598-04cb-11e6-937e-cca4a44d36f6.png">
<img width="1396" alt="screen shot 2016-04-17 at 6 38 56 pm" src="https://cloud.githubusercontent.com/assets/12897564/14590569/ed2fcad8-04cb-11e6-823b-25cc275d6650.png">
<img width="1399" alt="screen shot 2016-04-17 at 6 39 30 pm" src="https://cloud.githubusercontent.com/assets/12897564/14590568/e5dce5a4-04cb-11e6-8dda-f90f0243cab0.png">
<img width="1396" alt="screen shot 2016-04-17 at 6 39 41 pm" src="https://cloud.githubusercontent.com/assets/12897564/14590567/de753f96-04cb-11e6-843c-766007304d28.png">
<img width="1395" alt="screen shot 2016-04-17 at 6 39 52 pm" src="https://cloud.githubusercontent.com/assets/12897564/14590566/d8f5f808-04cb-11e6-846c-c5e34a435cb7.png">

**Comment by compassface** [comment]
this is weird

https://github.com/twbs/bootstrap/issues/306
