### ISSUE TITLE
strange little UI bug on the involcrate page

### ISSUE THREAD

**Issue by joshuarichard** [joshuarichard/amgg#314]
looks like the create account form is hiding underneath the transparent navbar?

<img width="1440" alt="screen shot 2016-04-20 at 12 45 07 am" src="https://cloud.githubusercontent.com/assets/12897564/14663646/38e1d644-0691-11e6-9249-2c2ad407a40c.png">

**Comment by jacobbuettner** [comment]
Taken care of by commit 32331d7 on GH252
