### ISSUE TITLE
Not logging user in after successful account creation - checkout.html

### ISSUE THREAD

**Issue by jacobbuettner** [joshuarichard/amgg#316]
Possible bug, after an account is successfully created the the user should be logged in but I got a 409 error when the create account process tried to log me in with my new account.  The new account was created and I could log in with the new credentials afterwards.  Only experienced this on the checkout page.  Can someone just check this out and see if they have the same issue.  If it works go ahead and close this issue.  If you have the same issue I had let me know.

**Comment by compassface** [comment]
![image](https://cloud.githubusercontent.com/assets/8681399/14681854/e36377c6-06f0-11e6-9f23-450ee5c34b56.png)

**Comment by compassface** [comment]
getting a 401 at  create account

**Comment by compassface** [comment]
![image](https://cloud.githubusercontent.com/assets/8681399/14682120/1250f3f0-06f2-11e6-86e6-abd3ff636c9d.png)

**Comment by compassface** [comment]
my passwords getting logged for some reason also
