### ISSUE TITLE
Misc bugs

### ISSUE THREAD

**Issue by jacobbuettner** [joshuarichard/amgg#318]
Some misc bugs I'm fixing.  Child hobbies was not getting pulled from the DB because pasatiempos was spelled wrong. Changing pastiempos to the correct spelling pasatiempos.  We were adding data:image/jpeg;base64, prefix to pictures on the client side, the correct way to store pictures is with that prefix so taking out that client side coding and just adding pictures to the DB with the data:image/jpeg;base64, prefix.

**Comment by joshuarichard** [comment]
merged
