### ISSUE TITLE
"Cesta" in cart link 

### ISSUE THREAD

**Issue by compassface** [joshuarichard/amgg#326]

**Comment by jacobbuettner** [comment]
![image](https://cloud.githubusercontent.com/assets/8673790/14931018/3a181670-0e36-11e6-893d-3dfd0275c513.png)

**Comment by jacobbuettner** [comment]
Couple things I noticed, its not on all pages (checkout, account, index, apradrina), It will not say Cesta if there is nothing in the cart and the user is not logged in.
