### ISSUE TITLE
Build a very basic "sponsor a child" page

### ISSUE THREAD

**Issue by joshuarichard** [joshuarichard/amgg#33]
When we click on "Donor" we want to have a page come up that dynamically and randomly lists 20 or so children that can be sponsored.

For now, create an html page, fill it in with static content, and make an api call to get one child that's unsponsored. Querying mongoDB for children with the unsponsored flag set to false should be good.

**Comment by jacobbuettner** [comment]
Static child sponsorship page has already been made by Carlos here: http://es.amgg.org/involucrate.html#Apadrina

**Comment by joshuarichard** [comment]
Done after #39 was merged
