### ISSUE TITLE
put the confirm terms check box in a more see-able place

### ISSUE THREAD

**Issue by joshuarichard** [joshuarichard/amgg#340]

**Comment by jacobbuettner** [comment]
Are we talking about this check box?  If so, did Brian give any input as to where he wants it.  It seems like a logical place to put it...

![image](https://cloud.githubusercontent.com/assets/8673790/15449028/65266efa-1f40-11e6-96ce-287b3a428219.png)

**Comment by jacobbuettner** [comment]
![image](https://cloud.githubusercontent.com/assets/8673790/15515900/43ca8626-21be-11e6-9412-b7a66eae0492.png)

**Comment by jacobbuettner** [comment]
![image](https://cloud.githubusercontent.com/assets/8673790/15516005/c7635c06-21be-11e6-83ab-d93369847ef8.png)
