### ISSUE TITLE
Populate child selection page from DB

### ISSUE THREAD

**Issue by jacobbuettner** [joshuarichard/amgg#44]
Populate the children's pictures used in the child selection page from MongoDB

**Comment by jacobbuettner** [comment]
Right now the mongo query will just pull all children.  Later on we should be able to pull children based on location, age, gender, etc.

**Comment by joshuarichard** [comment]
you're going to get some `no-undef` eslint errors on jquery's `$`'s. to fix that put `/* eslint no-undef: 0 */` at the top of children.js

**Comment by jacobbuettner** [comment]
Change child selection page to look like this: 
![image](https://cloud.githubusercontent.com/assets/8673790/12355048/0f88acc4-bb68-11e5-9468-7f944d426562.png)

**Comment by joshuarichard** [comment]
cleaning up IRC. this is outdated. reference: https://github.com/joshuarichard/amgg/issues/87
