### ISSUE TITLE
Turn mock pages into dynamic pages

### ISSUE THREAD

**Issue by jacobbuettner** [joshuarichard/amgg#46]
Changes the static mock pages I create (children.html, checkout.html, etc.) into dynamically populated pages.  Add server calls and maybe some cookies stuff.

**Comment by jacobbuettner** [comment]
Children images should come from DB
Children you are sponsoring should be populated from previous pg, either server or cookies
If logged in, info should populate the checkout forms

**Comment by joshuarichard** [comment]
can you clarify this issue? i'm confused about the specific purpose of it.
