### ISSUE TITLE
Add multiple child selection functionality

### ISSUE THREAD

**Issue by jacobbuettner** [joshuarichard/amgg#60]
Add functionality to the child selection page to allow donors to select multiple children to sponsor at once.  All selected children's information should be passed to the checkout form when the sponsor navigated to that page.

**Comment by joshuarichard** [comment]
right now this will work with localStorage. a donor clicks a child on the carousel, is brought to the checkout page. want to sponsor another child? no problem, click the button at the bottom that says something like 'agregar un nino' and you'll be brought back to the children page to select another child.
