### ISSUE TITLE
Add home button to all pages in the top left header

### ISSUE THREAD

**Issue by joshuarichard** [joshuarichard/amgg#62]
many pages have a link to the homepage but the checkout page looks like it's missing a link back
`localhost:3000/home`:
<img width="1200" alt="screen shot 2016-01-04 at 5 16 34 pm" src="https://cloud.githubusercontent.com/assets/12897564/12102155/f272dfb0-b306-11e5-91f5-e18e64d7fe03.png">

`localhost:3000/home/views/checkout.html`:
<img width="1198" alt="screen shot 2016-01-04 at 5 16 25 pm" src="https://cloud.githubusercontent.com/assets/12897564/12102154/f26e8e38-b306-11e5-9e8f-6000b616b92f.png">

**Comment by joshuarichard** [comment]
is this still valid?

**Comment by jacobbuettner** [comment]
I think it would make sense to add a home button on the top left on all pages.  I know the AMG logo on the footer links back to index.html but it's standard for the home button to be on the top left.

**Comment by joshuarichard** [comment]
merged in #240
