### ISSUE TITLE
Rebuild Child page to fit World Vision aesthetic

### ISSUE THREAD

**Issue by compassface** [joshuarichard/amgg#87]
Brian wanted something a little different than we had intended

![image](https://cloud.githubusercontent.com/assets/8681399/12369494/291a0aa8-bbc6-11e5-8716-3b67dbfce849.png)

**Comment by jacobbuettner** [comment]
@compassface will be working on this with me

**Comment by jacobbuettner** [comment]
We may want to use this carousel template for our page
 https://getbootstrap.com/examples/carousel/

**Comment by jacobbuettner** [comment]
Here what I'm thinking for the pick a child page layout 
![image](https://cloud.githubusercontent.com/assets/8673790/12373826/a1ba7ca6-bc55-11e5-9106-05f70b9bb831.png)

**Comment by jacobbuettner** [comment]
Here is the layout we settled on:
![image](https://cloud.githubusercontent.com/assets/8673790/12501536/55cbf51e-c08c-11e5-994f-65d252290257.png)

**Comment by jacobbuettner** [comment]
TODO:
- make page scale for different sizes
- test across browsers

**Comment by joshuarichard** [comment]
this was unreal.. all merged #101
